// Code generated by hertz generator.

package content

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	content "github.com/dgdts/UniversalServer/biz/model/content"
)

// CreateContent .
// @router /api/v1/content [POST]
func CreateContent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req content.ContentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(content.ContentResponse)

	c.JSON(consts.StatusOK, resp)
}
