// Code generated by hertz generator.

package content

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	biz_content "github.com/dgdts/UniversalServer/biz/content"
	content "github.com/dgdts/UniversalServer/biz/model/content"
	"github.com/dgdts/UniversalServer/internal/response"
)

// CreateContent .
// @router /api/v1/content [POST]
func CreateContent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req content.ContentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := biz_content.CreateContent(ctx, &req, c)
	if err != nil {
		response.JSONError(c, err)
		return
	}

	response.JSONSuccess(c, resp)
}
