// Code generated by hertz generator.

package binary

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	binaryBiz "github.com/dgdts/CloudNoteServer/biz/binary"
	"github.com/dgdts/CloudNoteServer/internal/response"
)

// GetUploadToken .
// @router /api/v1/resources/upload/token [POST]
func GetUploadToken(ctx context.Context, c *app.RequestContext) {
	response.JSON(ctx, c, binaryBiz.GetUploadToken)
}
