// Code generated by hertz generator.

package share

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	share "github.com/dgdts/CloudNoteServer/biz/model/share"
)

// GetShareNote .
// @router /api/v1/share/note [GET]
func GetShareNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req share.GetShareNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(share.GetShareNoteResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListShareNoteComments .
// @router /api/v1/share/note/comments [GET]
func ListShareNoteComments(ctx context.Context, c *app.RequestContext) {
	var err error
	var req share.ListShareNoteCommentsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(share.ListShareNoteCommentsResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateShareNoteComment .
// @router /api/v1/share/note/comment [POST]
func CreateShareNoteComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req share.CreateShareNoteCommentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(share.CreateShareNoteCommentResponse)

	c.JSON(consts.StatusOK, resp)
}
