// Code generated by hertz generator.

package note

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listnotesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnotemetaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sharenoteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createnoteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletenoteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnoteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatenoteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _noteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesharenoteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createorupdatesharenoteMw() []app.HandlerFunc {
	// your code...
	return nil
}
