// Code generated by hertz generator.

package binary

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourcesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuploadtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}
